#!/bin/sh

if test -e "$HOME"/.config/danora/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
#/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 ) # This fails
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "20"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "25"


echo "# Installing Lutris"
/usr/bin/flatpak install --user --noninteractive flathub net.lutris.Lutris
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Lutris Failed"
        exit 1
fi
echo "40"

echo "# Installing Steam"
/usr/bin/flatpak install --user --noninteractive flathub com.valvesoftware.Steam
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Steam Failed"
        exit 1
fi
echo "50"

echo "# Installing ProtonUp-Qt"
/usr/bin/flatpak install --user --noninteractive flathub net.davidotek.pupgui2
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing ProtonUp-Qt Failed"
        exit 1
fi
echo "55"


echo "# Installing LibreOffice"
/usr/bin/flatpak install --user --noninteractive flathub org.libreoffice.LibreOffice
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing LibreOffice Failed"
        exit 1
fi
echo "60"

echo "# Installing OnlyOffice"
/usr/bin/flatpak install --user --noninteractive flathub org.onlyoffice.desktopeditors
if [ "$?" != 0 ] ; then
        zenity --error \
            --text "Installing OnlyOffice Failed"
        exit 1
fi
echo "65"

echo "# Installing Bottles"
/usr/bin/flatpak install --user --noninteractive flathub com.usebottles.bottles
if [ "$?" != 0 ] ; then
        zenity --error \
            --text "Installing Bottles Failed"
        exit 1
fi
echo "70"

mkdir -p "$HOME"/.local/share/applications
cd "$HOME"/Applications
mkdir -p Weylus
cd Weylus
wget https://github.com/H-M-H/Weylus/releases/latest/download/linux.zip
unzip ./linux.zip
printf \
"[Desktop Entry]\n
Encoding=UTF-8\n
Version=1.0\n
Type=Application\n
NoDisplay=false\n
Exec=$HOME/Applications/Weylus/weylus \%u\n
Name=Weylus\n
Comment=Control your PC with your tablet" > "$HOME"/.local/share/applications/weylus.desktop
echo "75"

echo "# Installing DejaDup Backup"
/usr/bin/flatpak install --user --noninteractive flathub org.gnome.DejaDup
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing DejaDup Failed"
        exit 1
fi
echo "80"

echo "# Installing Font Downloader"
/usr/bin/flatpak install --user --noninteractive flathub org.gustavoperedo.FontDownloader
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing FontDownloader Failed"
        exit 1
fi
echo "85"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "90"

echo "# Installing Celluloid Media Player"
/usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Celluloid Failed"
        exit 1
fi
echo "95"

echo "# Almost done..."
mkdir -p "$HOME"/.config/danora/
touch "$HOME"/.config/danora/firstboot-done
echo "100"

) | 
     
   zenity --progress --title="Danora Firstboot - Initial configuration" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
